# Site settings
title: Inertia

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nberserk.github.io/" # the base hostname & protocol for your site
twitter_username: darrenha
github_username:  nberserk

tag_page: '/tags/'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-gist

sass:
    style: :compressed

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            category: "default"
