# Site settings
title: Learning by Doing

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nberserk.github.io/" # the base hostname & protocol for your site
twitter_username: darrenha
github_username:  nberserk

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-gist

sass:
    style: :compressed
