* bash
** if
#+BEGIN_SRC sh
  # checking first arg specified or not
  if [ -z "$1" ]; then    
      folder=sparkjob
  else
      folder=$1
  fi

  s1='a'
  s2='b'
  if [ "$s1" = "$s2" ];  then
      echo "equal"
  else
      echo 'not equal'
  fi

  #string compare
#+END_SRC

#+RESULTS:
: not equal

** nohup
DO NOT terminate background job, when i log off.
#+BEGIN_SRC bash
nohup /path/to/command-name arg1 arg2 &
#+END_SRC

* aws
** emr
- doesn't run when no default VPC is absent. https://aws.amazon.com/premiumsupport/knowledge-center/deleted-default-vpc/
- default vpc's 'DNS hostname' should be 'yes'. otherwise emr cluster will be terminated with error.

* avro
- http://avro.apache.org/docs/1.7.7/gettingstartedjava.html

* parquet 
parquet은 columnar storage format


schema resolution
if the reader's record schema has a field that contains a default value, and writer's schema does not have a field with the same name, then the reader should use the default value from its field.
if the reader's record schema has a field with no default value, and writer's schema does not have a field with the same name, an error is signalled.

avro spec
https://avro.apache.org/docs/1.7.7/spec.html

- http://www.slideshare.net/cloudera/hadoop-summit-36479635?qid=ae3b9f6c-0e8d-4403-8048-46c1fe3a4b47&v=qf1&b=&from_search=3
  - size 33p, speed comparison 34p

convert existing data into parquet :  http://blog.cloudera.com/blog/2014/05/how-to-convert-existing-data-into-parquet/

* org
- file link (org-insert-link)
** babel
- insert code block. <s <tab>
- run code block; C-c C-c

* emacs
- C-x C-e ; eval lisp last lexpr
** artist mode
you can draw rectangle using ascii. 
#+BEGIN_SRC lisp
;; enable mouse right button
(eval-after-load "artist"
   '(define-key artist-mode-map [(down-mouse-3)] 'artist-mouse-choose-operation)
   )
#+END_SRC

* spark sql
- subquery 
#+BEGIN_SRC sql
select value, cnt from  ( select value, count(*) as cnt from user group by d order by d ) inner
where inner.c > 5
#+END_SRC

* jekyll
on El-Capitan
gem install --user-install --bindir ~/bin --no-document --pre --verbose jekyll

https://github.com/jekyll/jekyll/issues/3984
